### DISCUSSION TITLE
ホーム画面で画面遷移がおかしいことがある

### DISCUSSION THREAD

**Discussion by yoshi389111** [increments/qiita-discussions#185] [要望・アイデア・不具合]
自分のホーム、あるいは他のユーザーのページにいって、何かのリンクをクリックすると、なぜかそのユーザーのピックアップ記事（複数ある場合には最後の記事）に飛んでしまうことがあります。

同じ操作をしても毎回発生するわけではなく、たまに発生するようですが。

画面を表示して、リンクを押すといきなり飛ぶこともありますし、画面を切り替える（例えば「記事」「質問」「LGTM」と並んでいる「質問」などに切り替えた後）にリンクを押した後に飛ぶこともあります。

（単に、何度かリロードしていると結果が変わるように思えます）

現在、ベータ版として「記事カードのUIの変更」が実施されていると思いますが、ベータ版でも、元の版でも発生するようです。

ちなみに、デベロッパーツールで見てみると、以下のようになっていました。

正常な場合：

```css
/* article 要素のクラス指定 */
.css-u56bup {
    background-color: #ffffff;
    cursor: pointer;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    padding: 16px 24px;
    position: relative;
}

/* a 要素のクラス指定 */
.css-32d82q {
    bottom: 0;
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
}
```

リンクがおかしい場合：
（ピックアップ記事の articleに `position: relative;` がないため、 a 要素が１画面分に広がっているみたい）

```css
/* article 要素のクラス指定 */
.css-81mxb5 {
    width: 100%;
    border-top: 1px solid rgba(0,0,0,0.12);
    padding: 16px;
}

/* a 要素のクラス指定 */
.css-32d82q {
    inset: 0px;
    position: absolute;
}
```

また、直接は関係ない気がしますが、何度かリロードしていると、アイコン（GitHubアイコンとかTwitterアイコンなどのSNSアイコン、タグマークのアイコンなど）が壊れて表示されることがあります。
リンクが正常な時にも、おかしい時も、アイコンが壊れて表示されることはあるようです。

念のため、発生した環境は Windows11 + Chrome 99.0.4844.82 と、Android 12 + Chrome 99.0.4844.73 です。
